/**
 * POST /api/access-code/validate
 *
 * Validates the access code entered by the admin user.
 * If valid, activates the ERANI Beta subscription for the organization:
 *   - Sets paid_subscription = true on organizations
 *   - Sets eris_balance = 100 on all profiles in the org
 *   - Marks access code as used
 *
 * Body: { code: string }  (e.g. "K9X2-R7WB-4M6P" or "K9X2R7WB4M6P")
 * Headers: Authorization: Bearer <token>
 */

import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { supabaseAdmin } from '@/lib/supabaseAdmin'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

function normalizeCode(input: string): string {
  // Remove all hyphens and whitespace, uppercase the result
  const clean = input.replace(/[-\s]/g, '').toUpperCase()
  // Reformat to XXXX-XXXX-XXXX
  if (clean.length !== 12) return input.toUpperCase()
  return `${clean.slice(0, 4)}-${clean.slice(4, 8)}-${clean.slice(8, 12)}`
}

export async function POST(request: Request): Promise<NextResponse> {
  try {
    // --- Auth ---
    const authHeader = request.headers.get('Authorization')
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'No autorizado' }, { status: 401 })
    }
    const token = authHeader.replace('Bearer ', '')

    const anonClient = createClient(supabaseUrl, supabaseAnonKey, {
      auth: { persistSession: false },
    })
    const { data: { user }, error: authError } = await anonClient.auth.getUser(token)
    if (authError || !user) {
      return NextResponse.json({ error: 'Token inválido' }, { status: 401 })
    }

    // --- Get body ---
    const body = await request.json().catch(() => ({}))
    const rawCode: string = body.code ?? ''

    if (!rawCode || rawCode.trim().length < 12) {
      return NextResponse.json({ error: 'Código inválido — debe tener 12 caracteres' }, { status: 400 })
    }

    const normalizedCode = normalizeCode(rawCode)

    // --- Fetch profile to get org_id ---
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('organization_id, profile_type')
      .eq('id', user.id)
      .single()

    if (profileError || !profile) {
      return NextResponse.json({ error: 'Perfil no encontrado' }, { status: 404 })
    }

    if (!profile.organization_id) {
      return NextResponse.json({ error: 'Usuario sin organización' }, { status: 400 })
    }

    // --- 1. Check activation_codes table (generated by Stripe Webhook) ---
    const cleanRaw = rawCode.replace(/[-\s]/g, '').toUpperCase()
    
    const { data: actCodeRecords, error: actError } = await supabaseAdmin
      .from('activation_codes')
      .select('*')
      .eq('status', 'pending')

    const actRecord = (actCodeRecords || []).find((r: any) => {
      const c = (r.code || '').replace(/[-\s]/g, '').toUpperCase()
      return c === cleanRaw || r.code === normalizedCode || r.code === rawCode.trim().toUpperCase()
    })

    if (actRecord) {
      // Mark activation code as claimed
      await supabaseAdmin
        .from('activation_codes')
        .update({
          status: 'claimed',
          claimed_at: new Date().toISOString(),
          claimed_by_user_id: user.id,
        })
        .eq('id', actRecord.id)

      // Activate organization subscription and ERIS balance
      await supabaseAdmin
        .from('organizations')
        .update({
          paid_subscription: true,
          subscription_activated_at: new Date().toISOString(),
          eris_balance: 100,
          plan: 'beta',
        })
        .eq('id', profile.organization_id)

      // Update all profiles in the organization to 100 ERIS
      await supabaseAdmin
        .from('profiles')
        .update({ eris_balance: 100 })
        .eq('organization_id', profile.organization_id)

      return NextResponse.json({
        success: true,
        message: 'Suscripción ERANI Beta activada correctamente',
      })
    }

    // --- 2. Fallback: Call the SQL validate_access_code function (access_codes) ---
    const { data: result, error: rpcError } = await supabaseAdmin
      .rpc('validate_access_code', {
        p_org_id: profile.organization_id,
        p_code: normalizedCode,
      })

    if (rpcError) {
      console.error('validate_access_code RPC error:', rpcError)
      return NextResponse.json({ error: 'Error interno al validar código' }, { status: 500 })
    }

    const rpcResult = result as { success: boolean; error?: string; message?: string }

    if (!rpcResult.success) {
      return NextResponse.json({
        success: false,
        error: rpcResult.error ?? 'Código inválido o ya utilizado',
      }, { status: 400 })
    }

    return NextResponse.json({
      success: true,
      message: rpcResult.message ?? 'Suscripción ERANI Beta activada',
    })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Error interno'
    console.error('[access-code/validate] Error:', message)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
